GORM supports several http://gorm.grails.org/latest/hibernate/manual/index.html#_multi_tenancy_modes[tenancy modes]. In this tutorial we use `DATABASE` where a separate database with a separate connection pool is used to store each tenants data.

Add the following configuration to `application.yml`


[source, yaml]
.books/src/main/resources/application.yml
----
include::{sourceDir}/books/src/main/resources/application.yml[tag=gorm]
----

<1> Use `DATABASE` mode.
<2> Use `HttpHeaderTenantResolver` which resolves the tenant ID from an HTTP header. Remember we configured the `gateway` microservice to propagate the tenant ID in an HTTP Header.

Create a GORM Entity to persist books:

[source, groovy]
.books/src/main/groovy/example/micronaut/Book.groovy
----
include::{sourceDir}/books/src/main/groovy/example/micronaut/Book.groovy[]
----

<1> GORM entities are annotated with `grails.persistence.Entity`.
<2> Use of `GormEntity` is merely to aid IDE support outside of Grails. When used inside a Grails context, some IDEs will use the grails-app/domain location as a hint to enable code completion.
<3> Implement the `MultiTenant` trait in the GORM entities you want to be regarded as multi tenant.